stages:
  cleaning:
    cmd: python3 ../../src/data/hyperparams_clean.py
    deps:
    - ../../src/data/hyperparams_clean.py
    - ../../data/raw/raw.csv
    outs:
    - ../../data/interim/hyperparams_clean_df.csv
  preprocess:
    cmd: python3 ../../src/features/hyperparams_preprocess.py
    deps:
    - ../../data/interim/hyperparams_clean_df.csv
    - ../../src/features/hyperparams_preprocess.py
    outs:
    - ../../data/processed/hyperparams_train_df.csv
    - ../../data/processed/hyperparams_test_df.csv
  experiment:
    cmd: python3 ../../src/experiments/hyperparameters_experiment.py
    deps:
    - ../../src/experiments/hyperparameters_experiment.py
    - ../../data/processed/hyperparams_train_df.csv
    - ../../data/processed/hyperparams_test_df.csv