channels:
- conda-forge
dependencies:
- python=3.9.17
- pip<=23.0.1
- pip:
  - mlflow==2.4
  - numpy==1.24.3
  - pandas==2.0.2
  - psutil==5.9.5
  - scikit-learn==1.2.2
  - scipy==1.11.1
  - typing-extensions==4.7.1
  - xgboost==1.7.6
name: mlflow-env
