services:
  mlflow-server:
    build: ./mlflow-server
    image: mlflow-server-image:1.0.0 
    container_name: "mlflow-server-container-1"
    ports:
      - "5000:5000"
    networks:
      - mlflow-network
    volumes:
      - ./mlruns-volume:/mlflow/mlruns
    tty: true
    command: bash -c "mlflow server --backend-store-uri sqlite:///mlruns/mlruns.db --default-artifact-root file:mlruns/artifacts --host 0.0.0.0 --port 5000"

  mlflow-client:
    build: ./mlflow-client-model
    image: mlflow-client-model-image:1.0.0
    container_name: "mlflow-client-container-model-1"
    networks:
      - mlflow-network
    volumes:
      - ./mlruns-volume:/mlflow/mlruns
    tty: true
    depends_on:
      - mlflow-server
    command: sh -c "dvc init --no-scm && dvc repro -R pipelines/"

networks:
  mlflow-network:

volumes:
  mlruns-volume: