stages:
  cleaning:
    cmd: python3 ../../src/model_3/cleaning.py
    deps:
    - ../../src/model_3/cleaning.py
    - ../../data/raw/data.csv
    outs:
    - ../../data/data_3/df_clean.csv
  preprocess:
    cmd: python3 ../../src/model_3/preprocessing.py
    deps:
    - ../../data/data_3/df_clean.csv
    - ../../src/model_3/preprocessing.py
    outs:
    - ../../data/data_3/df_train.csv
    - ../../data/data_3/df_test.csv
  train:
    cmd: python3 ../../src/model_3/train.py
    deps:
    - ../../src/model_3/train.py
    - ../../data/data_3/df_train.csv
    outs:
    - ../../models/model_3
  test:
    cmd: python3 ../../src/model_3/test.py
    deps: 
    - ../../src/model_3/test.py
    - ../../data/data_3/df_test.csv
    - ../../models/model_3
    metrics:
    - ../../metrics/metrics_3.json:
        cache: false
