stages:
  cleaning:
    cmd: python3 ../../src/data/catboost_clean.py
    deps:
    - ../../src/data/catboost_clean.py
    - ../../data/raw/raw.csv
    outs:
    - ../../data/interim/catboost_clean_df.csv
  preprocess:
    cmd: python3 ../../src/features/catboost_preprocess.py
    deps:
    - ../../data/interim/catboost_clean_df.csv
    - ../../src/features/catboost_preprocess.py
    outs:
    - ../../data/processed/catboost_train_df.csv
    - ../../data/processed/catboost_test_df.csv
  experiment:
    cmd: python3 ../../src/experiments/catboost_experiment.py
    deps:
    - ../../src/experiments/catboost_experiment.py
    - ../../data/processed/catboost_train_df.csv
    - ../../data/processed/catboost_test_df.csv