stages:
  cleaning:
    cmd: python3 ../../src/model_2/cleaning.py
    deps:
    - ../../src/model_2/cleaning.py
    - ../../data/raw/data.csv
    outs:
    - ../../data/data_2/df_clean.csv
  preprocess:
    cmd: python3 ../../src/model_2/preprocessing.py
    deps:
    - ../../data/data_2/df_clean.csv
    - ../../src/model_2/preprocessing.py
    outs:
    - ../../data/data_2/df_train.csv
    - ../../data/data_2/df_test.csv
  train:
    cmd: python3 ../../src/model_2/train.py
    deps:
    - ../../src/model_2/train.py
    - ../../data/data_2/df_train.csv
    outs:
    - ../../models/model_2
  test:
    cmd: python3 ../../src/model_2/test.py
    deps: 
    - ../../src/model_2/test.py
    - ../../data/data_2/df_test.csv
    - ../../models/model_2
    metrics:
    - ../../metrics/metrics_2.json:
        cache: false
